// ISR - Interrupt Service Routines

#include "stm32f4xx_hal.h"
#include "hal_isr.h"

ISR_DUMMY_HANDLER_PRINTF_NORET(NMI)
ISR_DUMMY_HANDLER_PRINTF_NORET(HardFault)
ISR_DUMMY_HANDLER_PRINTF_NORET(MemManage)
ISR_DUMMY_HANDLER_PRINTF_NORET(BusFault)
ISR_DUMMY_HANDLER_PRINTF_NORET(UsageFault)
ISR_DUMMY_HANDLER_PRINTF(SVC)
ISR_DUMMY_HANDLER_PRINTF(DebugMon)
ISR_DUMMY_HANDLER_PRINTF(PendSV)

void SysTick_Handler(void)
{
  HAL_IncTick();
}

void EXTI1_IRQHandler(void)
{
  HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_1);
}
